// bid Today
export const BidToday = [
    {
        name: 'Bientôt disponible',
        image: require('../assets/images/product-bid1.png'),
        price: '600€',
        priceCoconut: '= 6000',
        unblock: '50',
    },
    {
        name: 'Bientôt disponible',
        image: require('../assets/images/product-bid2.png'),
        price: '130€',
        priceCoconut: '= 13 000',
        unblock: '100',
    },
    {
        name: 'Bientôt disponible',
        image: require('../assets/images/product-bid3.png'),
        price: '250€',
        priceCoconut: '= 25 000',
        unblock: '200',
    },
    {
        name: 'Bientôt disponible',
        image: require('../assets/images/product-bid4.png'),
        price: '490€',
        priceCoconut: '= 49 000',
        unblock: '500',
    },
]

// History Bid

export const HistoryBid = [
    {
        name: 'Manette Playstion 4',
        image: require('../assets/images/product-history1.png'),
        winner: 'Jacques la malice',
        avatar: require('../assets/images/user-image.png'),
        comeFrom: 'Paris',
        price: '600€',
        priceCoconut: '= 6000',
        participation: 'Oui',
        timeToday: '19/03/24',
        timeYesterday: '18/03/24',
        bid: '156',
        sell: '2 540',
        back: '+ 15',
    },
    {
        name: 'Nintendo Switch',
        image: require('../assets/images/product-history2.png'),
        winner: 'Jacques la malice',
        avatar: require('../assets/images/user-image.png'),
        comeFrom: 'Paris',
        price: '130€',
        priceCoconut: '= 13 000',
        participation: 'Non',
        timeToday: '19/03/24',
        timeYesterday: '18/03/24',
        bid: '123',
        sell: '9 300',
        back: '0',
    },{
        name: 'Sac à main Gucci',
        image: require('../assets/images/product-history3.png'),
        winner: 'Jacques la malice',
        avatar: require('../assets/images/user-image.png'),
        comeFrom: 'Paris',
        price: '250€',
        priceCoconut: '= 25 000',
        participation: 'Oui',
        timeToday: '19/03/24',
        timeYesterday: '18/03/24',
        bid: '365',
        sell: '11 300',
        back: '+ 10',
    },{
        name: 'Playstation 4',
        image: require('../assets/images/product-history4.png'),
        winner: 'Jacques la malice',
        avatar: require('../assets/images/user-image.png'),
        comeFrom: 'Paris',
        price: '490€',
        priceCoconut: '= 49 000',
        participation: 'Oui',
        timeToday: '19/03/24',
        timeYesterday: '18/03/24',
        bid: '893',
        sell: '23 670',
        back: '+ 20',
    },
]
